//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentation
    {
        public int Id { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> ClassroomID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
