//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionOfStudent
    {
        public int Id { get; set; }
        public string AnswerOfStudent { get; set; }
        public Nullable<bool> IsTrue { get; set; }
        public int ExamOfStudentID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ExamOfStudent ExamOfStudent { get; set; }
    }
}
